//! seck-release-sign: SLH-DSA signs a file with a secret key.
//!
//! Usage: seck-release-sign --key <sk.bin> --in <artifact> --out <sig.bin>
//!
//! The secret key is the raw byte form of an SLH-DSA-SHAKE-128s key
//! generated by seck-crypto::sign::slh_dsa_keypair(). In production the
//! key lives only on an air-gapped machine; see docs/RELEASE_KEY.md.

use anyhow::Context;
use clap::Parser;
use std::path::PathBuf;

#[derive(Parser)]
struct Args {
    #[arg(long)]
    key: PathBuf,
    #[arg(long, name = "in")]
    input: PathBuf,
    #[arg(long, name = "out")]
    output: PathBuf,
}

fn main() -> anyhow::Result<()> {
    let a = Args::parse();
    let sk = std::fs::read(&a.key).with_context(|| format!("read key {:?}", a.key))?;
    let msg = std::fs::read(&a.input).with_context(|| format!("read input {:?}", a.input))?;
    let sig = seck_crypto::sign::slh_dsa_sign(&sk, &msg);
    std::fs::write(&a.output, &sig).with_context(|| format!("write sig {:?}", a.output))?;
    eprintln!(
        "signed: {} bytes sig over {} bytes input",
        sig.len(),
        msg.len()
    );
    Ok(())
}
